version: '2'
services:
  train-flask:
    build: ${PWD}
    container_name: train-flask
    restart: on-failure
    ports:
      - 5000:5000
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
    
  snips:
    build: ${PWD}/snips-voicehat
    container_name: snips
    ports:
      - 1883:1883
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ${PWD}/snips-voicehat/assistant:/usr/share/snips/assistant
      - ${PWD}/snips-voicehat/skills:/var/lib/snips/skills
    depends_on:
      - train-flask
    command: "--include-components snips-asr,snips-audio-server,snips-tts,snips-hotword,snips-dialogue,snips-analytics,snips-nlu,snips-skill-server"
