# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Train(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, driver=None, status=None):  # noqa: E501
        """Train - a model defined in OpenAPI

        :param id: The id of this Train.  # noqa: E501
        :type id: int
        :param name: The name of this Train.  # noqa: E501
        :type name: str
        :param driver: The driver of this Train.  # noqa: E501
        :type driver: str
        :param status: The status of this Train.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'driver': str,
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'driver': 'driver',
            'status': 'status'
        }

        self._id = id
        self._name = name
        self._driver = driver
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Train':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Train of this Train.  # noqa: E501
        :rtype: Train
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Train.


        :return: The id of this Train.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Train.


        :param id: The id of this Train.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Train.


        :return: The name of this Train.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Train.


        :param name: The name of this Train.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def driver(self):
        """Gets the driver of this Train.


        :return: The driver of this Train.
        :rtype: str
        """
        return self._driver

    @driver.setter
    def driver(self, driver):
        """Sets the driver of this Train.


        :param driver: The driver of this Train.
        :type driver: str
        """

        self._driver = driver

    @property
    def status(self):
        """Gets the status of this Train.


        :return: The status of this Train.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Train.


        :param status: The status of this Train.
        :type status: str
        """

        self._status = status
